config/routes.rb
Four04kids::Application.routes.draw do
  mount Afterparty::Engine, at: "afterparty", as: "afterparty_engine"
  root 'static_pages#home'

  get 'about' => 'static_pages#about', as: :about
  get 'stories' => 'static_pages#stories', as: :stories
  get 'donate' => 'static_pages#donate', as: :donate
  get 'docs' => 'static_pages#docs', as: :docs

  get "api/random"
  get "api/index"
  get "api/show"

end

app/models/kid.rb
class Kid < ActiveRecord::Base
  before_validation :create_full_address
  before_validation :generate_image_url

  validates_presence_of :first_name
  validates_presence_of :last_name
  validates_presence_of :missing_state
  validates_presence_of :image_url

  geocoded_by :address
  before_save :geocode, :if => :address_changed?

  default_scope -> { where("age > 0") }
  scope :excluding, -> (id) { where("id != ?", id.to_i) }
  scope :random, -> { order("RANDOM()").limit(1).first }
  scope :near_location, -> (location, limit) {
    near([location.latitude, location.longitude], limit)
  }

  def full_name
    "#{self.first_name} #{self.middle_name} #{last_name}"
  end

  def create_full_address
    unless self.missing_city.blank? && self.missing_state.blank?
      self.address = "#{self.missing_city}, #{self.missing_state}"
    else
      self.address = self.missing_state
    end
  end

  def add_hostname_to_url(hostname, url)
    base = self.send(url.to_sym)
    self.send("#{url.to_sym}=",  "#{hostname}#{base}")
  end

  def method_missing(method, *args, &block)
    if method.to_s =~ /^fullname$/
      self.full_name
    else
      super
    end
  end

  def generate_image_url
    if self.thumbnail_url
      self.image_url = self.thumbnail_url.gsub(/t\./, ".")
    end
  end

  def missing_url
    "http://www.missingkids.com/missingkids/servlet/PubCaseSearchServlet?act=viewPoster&caseNum=#{self.case_number}&orgPrefix=#{self.org_prefix}"
  end

  def increment(by = 1)
    self.views ||= 0
    self.views += by
    self.save
  end

  def increment!(by=1)
    job = Afterparty::BasicJob.new @kid, :increment
    Rails.configuration.queue << job
  end

  def description
    "#{full_name.upcase}, AGE: #{age}, MISSING: #{missing_date}"
  end
end

app/controllers/api_controller.rb
class ApiController < ApplicationController
  before_filter :set_access_control_headers
  def random
    if location.country_code == "US"
      @limit = params[:limit].blank? ? 500 : params[:limit].to_i
      @query = Kid.near_location(location, @limit)
    else
      @query = Kid.all
    end
    @query = @query.excluding(params[:exclude]) if params[:exclude]
    @kid = @query.random
    @kid.increment!
    render json: @kid, meta: {location: location.data}
  end

  def index
    @kids = Kid.where(api_params).paginate(pagination_params)
    @kids = @kids.order("missing_date DESC")
    render json: @kids
  end

  def show
  end

  private

  def set_access_control_headers
    headers['Access-Control-Allow-Origin'] = '*'
    headers['Access-Control-Request-Method'] = '*'
  end

  def api_params
    params.permit(:sex, :missing_state)
  end

  def pagination_params
    if params[:per_page]
      @per_page = [params[:per_page].to_i, 100].min
    else
      @per_page = 100
    end
    {
      page: params[:page] || 1,
      per_page: @per_page
    }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def location
    if params[:location].blank?
      if Rails.env.test? || Rails.env.development?
        @location ||= Geocoder.search("50.78.167.161").first
      else
        @location ||= request.location
      end
    else
      params[:location].each {|l| l = l.to_i } if params[:location].is_a? Array
      @location ||= Geocoder.search(params[:location]).first
      allowed = [:latitude, :longitude, :address, :city]
      puts @location.methods
      @location
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
    fetch_kids
  end

  def about
    fetch_kids(6)
  end

  def stories
    fetch_kids(6)
  end

  def donate
    fetch_kids(6)
  end

  def docs
    fetch_kids(6)
  end

  private

  def fetch_kids(number_of_entries = 30)
    if params[:location].blank?
      @location_query = [location.latitude, location.longitude]
      @city = request.location.city
    else
      @location_query = params[:location]
      @city = params[:city]
    end
    @kids = Kid.limit(50).near(@location_query, 500)
    @kids = @kids.to_a.slice(0,number_of_entries).shuffle
  end
end

app/helpers/api_helper.rb
module ApiHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def request_city
    if params[:location].blank?
      if request.location.city.blank?
        "Seattle"
      else
        request.location.city
      end
    else
      params[:location]
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />
  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

  	<title><%= content_for?(:title) ? yield(:title) : "404kids - Missing Kids on Missing Pages" %></title>

  	<%= stylesheet_link_tag    "application" %>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
    <%= analytics_init if Rails.env.production? %>
  </head>
  <body>

    <%= yield %>

    <%= javascript_include_tag "application" %>
    <%= content_for :js %>
  </body>
</html>

app/views/static_pages/_nav_header.html.erb
<div class="row">
  <div class="home-images">
    <div class="large-12 columns titlebar">
      <h2>Missing Persons Near
      <input value="<%= request_city %>">
      </h2>
    </div>
    <div class="large-12 columns">
      <div class="first-block block"></div>
      <% @kids.each_with_index do |kid, index| %>
        <% clazz = index >= 5 ? " last-row" : '' %>
        <a class="bw block<%= clazz %>" style="background-image: url('http://missingkids.com/<%=kid.image_url%>');"
          data-name="<%= "#{kid.first_name} #{kid.last_name}" %>" data-location="<%= kid.create_full_address %>"
          href="<%= kid.missing_url %>" target="_blank" data-timeago="<%= time_ago_in_words kid.missing_date %>"
          data-age="<%= kid.age %>" data-partial="true"
          ></a>
      <% end %>
      <div class="block logo last-block"></div>
      <div class="popup"></div>
    </div>
  </div>
</div>
<div class="row news-row">
  <div class="large-12 columns newsfeed">
    <span><%= @kids.collect(&:description).join(" // ") %></span>
  </div>
</div>
<header class="row">
  <ul class="nav">
    <%= render "nav_links" %>
  </ul>
  <ul class="social">
    <%= render "social_links" %>
  </ul>
</header>

app/views/static_pages/_nav_links.html.erb
<li class="<%= params[:action] == "home" ? "active" : "" %>"><a href="<%= root_path %>">Home</a></li>
<li class="<%= params[:action] == "about" ? "active" : "" %>"><a href="<%= about_path %>">About</a></li>
<li class="<%= params[:action] == "stories" ? "active" : "" %>"><a href="<%= stories_path %>">Stories</a></li>
<li class="<%= params[:action] == "donate" ? "active" : "" %>"><a href="<%= donate_path %>">Donate</a></li>
<li class="<%= params[:action] == "docs" ? "active" : "" %>"><a href="<%= docs_path %>">Docs</a></li>

app/views/static_pages/_social_links.html.erb
<li><a href="/404" class="google"></a></li>
<li><a href="https://twitter.com/404kidsorg" class="twitter"></a></li>
<li><a href="https://www.facebook.com/pages/404Kids/164500173753726" class="facebook"></a></li>
<li><a href="https://github.com/theverything/four04kids" class="github"></a></li>

app/views/static_pages/about.html.erb
<%= render "nav_header" %>
<div class="row" id="main">
  <div class="large-12 columns main">
    <div class="description">
      <p>404Kids is a team of technology professionals dedicated to supporting America’s search for missing and exploited children. Through the previously underutilized space of 404 (not found) pages, 404Kids intends to elevate the visibility, and awareness of, missing children.</p>

      <p>We are a resource for families, law enforcement, and the victimized youth with whom Americans unknowingly coexist. 404Kids is possible through users and businesses who consciously channel the power of pages they never intended to use.</p>
    </div>
    <a class="add-widget" href="/404">Add Our Widget</a>
  </div>
</div>

app/views/static_pages/docs.html.erb
<%= render "nav_header" %>
<div class="row" id="main">
  <div class="large-12 columns main">
    <p>Below is the JavaScript necessary for incorporating missing child listings onto your website’s 404 pages; a simple gesture that aligns your organization with thousands of families and individuals already committed to broader publicity and hope for missing children.</p>

    <pre class="embed-code"><%= "<script id='kids404-script' src=\"https://s3.amazonaws.com/404kids/src/embed.js\" type=\"text/javascript\"></script>" %></pre>

    <br>
    <p><a href="https://github.com/theverything/four04kids">Visit us on Github</a> for API and widget documentation</p>

    <p>404Kids is devoted to maintaining an open-source, secure vehicle for bringing your pages onboard, and for assistance or questions of any kind, please contact <a href="mailto:404kids@gmail.com">404Kids</a>.</p>
  </div>
</div>

app/views/static_pages/donate.html.erb
<%= render "nav_header" %>
<div class="row" id="main">
  <div class="large-12 columns main">
    <p>If you feel compelled to aid in the search for missing and exploited children, please join our partnership of awareness by adding the 404Kids widget to your website’s 404 pages. The reach of the 404Kids apparatus is entirely dependent on the compassion of those who choose to prioritize missing children as a part of their business and personal identities.</p>

    <p>404Kids also accepts financial and service-based donations.</p>
  </div>
</div>

app/views/static_pages/home.html.erb
<div class="row">
  <div class="home-images">
    <div class="large-12 columns titlebar">
      <h2>Missing Persons Near
      <input value="<%= request_city %>">
      </h2>
    </div>
    <div class="large-12 columns">
      <div class="first-block block"></div>
      <% @kids.each_with_index do |kid, index| %>
        <% clazz = index >= 23 ? " last-row" : '' %>
        <a class="bw block<%= clazz %>" style="background-image: url('http://missingkids.com/<%=kid.image_url%>');"
          data-name="<%= "#{kid.first_name} #{kid.last_name}" %>" data-location="<%= kid.create_full_address %>"
          href="<%= kid.missing_url %>" target="_blank" data-timeago="<%= time_ago_in_words kid.missing_date %>"
          data-age="<%= kid.age %>"
          ></a>
      <% end %>
      <div class="block logo last-block"></div>
      <div class="popup"></div>
    </div>
  </div>
</div>
<div class="row news-row">
  <div class="large-12 columns newsfeed">
    <span><%= @kids.collect(&:description).join(" // ") %></span>
  </div>
</div>
<footer class="row">
  <ul class="nav">
    <%= render "nav_links" %>
  </ul>
  <ul class="social">
    <%= render "social_links" %>
  </ul>
</footer>

app/views/static_pages/stories.html.erb
<%= render "nav_header" %>
<div class="row" id="main">
  <div class="large-12 columns main">
    <p>“There can be no keener revelation of a society’s soul than the way in which it treats its children” -Nelson Mandela</p>

    <p>The success of the 404Kids network is contingent upon the participation and contribution of likeminded people and organizations across the Internet. In solidarity with this community’s commitment to helping missing and exploited children, 404Kids celebrates stories of recovery the nation over.</p>
  </div>
</div>